platform :ios, '10.0'
use_frameworks!

target 'xywy_swift' do

 pod 'Alamofire',   '~> 4.4'
 pod 'RxSwift',     '~> 3.0'
 pod 'RxCocoa',     '~> 3.0'
 pod 'Kingfisher',  '~> 3.0'
 pod 'SnapKit',     '~> 3.2.0'
 pod 'BSImagePicker', '~> 2.4'
 pod 'PullToRefresher', '~> 2.0'
 pod 'SwiftyJSON'
end
